# Generated by Django 5.2.4 on 2025-07-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_phone1', models.BigIntegerField()),
                ('number_phone2', models.BigIntegerField()),
                ('post_code', models.BigIntegerField()),
                ('addres', models.TextField()),
            ],
        ),
    ]
