# Generated by Django 5.2.4 on 2025-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_acount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='number_phone1',
            field=models.BigIntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='acount',
            name='number_phone2',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
