# Generated by Django 5.2.4 on 2025-07-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_comments_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay', to='shopping.comments'),
        ),
    ]
