# Generated by Django 5.2.4 on 2025-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_chat_page_remove_chat_user_chat_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='is_read',
            new_name='admin_read',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_read',
            field=models.BooleanField(default=False),
        ),
    ]
