# Generated by Django 5.2.4 on 2025-08-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_rename_is_read_chat_admin_read_chat_user_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture_black',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_blue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_brown',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_green',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_red',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_silver',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_white',
        ),
    ]
